# Generated by Django 4.1.5 on 2023-02-22 18:56

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrewSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "measurement_type",
                    models.TextField(
                        choices=[("imperial", "Imperial"), ("metric", "Metric")],
                        default="imperial",
                        max_length=10,
                    ),
                ),
                ("batch_size", models.FloatField(default=5)),
                ("boil_time", models.FloatField(default=60)),
                ("brewhouse_efficiency", models.FloatField(default=65)),
                ("water_loss_per_grain_unit", models.FloatField(default=0.5)),
                ("water_loss_fermentor_trub", models.FloatField(default=0.25)),
                ("water_loss_kettle_trub", models.FloatField(default=0.25)),
                ("water_loss_per_boil_unit", models.FloatField(default=1.5)),
                ("do_sparge", models.BooleanField(default=False)),
                ("mash_thickness_target", models.FloatField(default=1.3)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
