# Generated by Django 4.1.5 on 2024-01-12 21:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("brew_log", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brewlog",
            name="recipe",
        ),
    ]
