# Generated by Django 4.1.5 on 2024-01-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brew_log", "0003_remove_brewlog_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="brewlog",
            name="recipe",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
