# Generated by Django 4.1.5 on 2024-01-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brew_log", "0004_brewlog_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gravityreading",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
