# Generated by Django 4.1.5 on 2023-02-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="batch_size",
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="boil_time",
            field=models.FloatField(default=60),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="brewhouse_efficiency",
            field=models.FloatField(default=65),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="do_sparge",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="mash_thickness_target",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="measurement_type",
            field=models.TextField(
                choices=[("imperial", "Imperial"), ("metric", "Metric")],
                default="imperial",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="water_loss_fermentor_trub",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="water_loss_kettle_trub",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="water_loss_per_boil_unit",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="water_loss_per_grain_unit",
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
