# Generated by Django 4.1.5 on 2023-02-01 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemistry',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemistry', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultures', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='fermentable',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fermentables', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='hop',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hops', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='nonfermentable',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_fermentables', to='recipes.recipe'),
        ),
    ]
