# Generated by Django 4.1.5 on 2023-02-02 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profiles", "0002_userprofile_batch_size_userprofile_boil_time_and_more"),
        ("recipes", "0002_alter_chemistry_recipe_alter_culture_recipe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chemistry",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chemistry",
            name="timing",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="culture",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="culture",
            name="timing",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fermentable",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fermentable",
            name="timing",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hop",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hop",
            name="timing",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nonfermentable",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nonfermentable",
            name="timing",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="author",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="batch_size",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="efficiency",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to="user_profiles.userprofile",
            ),
        ),
    ]
